version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group updates for similar dependencies together
    groups:
      npm-dependencies:
        patterns:
          - "*"
    # Labels to add to pull requests
    labels:
      - "dependencies"
      - "javascript"
    # Automatically merge minor and patch updates
    commit-message:
      prefix: "chore"
      include: "scope"
    # Open pull requests for security updates
    open-pull-requests-limit: 10
    # Allow updates to pre-release versions
    allow:
      - dependency-type: "all" 